name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *" 
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: Platane/snk@v3
        with:
          github_user_name: Kxrma47 
          outputs: dist/snake.svg
      - name: Upload Snake Animation
        uses: actions/upload-artifact@v3
        with:
          name: snake-animation
          path: dist/snake.svg

      - name: Push Snake Animation to README
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A
          git commit -m "Generated snake animation"
          git push
